### PR TITLE
Revert "fix calculation of dropdown position in a scrolling dropdownP…

### PR DESCRIPTION
**Pull request by david-knipe395**
Revert "fix calculation of dropdown position in a scrolling dropdownParent"

This reverts commit 5c12f152ebfc914e0b515bc7b32e16c945a2d9cc.

trac #37945

This pull request includes a

- Bug fix

The following changes were made

- Revert 5c12f152ebfc914e0b515bc7b32e16c945a2d9cc. This fixed the positioning of dropdowns in some cases where the dropdown parent was scrolled, but broke it in other cases (I think, where the dropdown parent was the body and was scrolled).

trac #37945

### CODE REVIEW

**Comment by jayaddison** [comment]
:wave: Hello - I noticed this pull request while digging around some recently-closed pull requests on `select2/select2`.  Some recommendations:

If this is a problem that _hasn't_ previously been reported, then the relevant (non-company-internal) details from the original defect are worth including as part of a [new issue report in `select2`](https://github.com/select2/select2/issues/new).

If it has been already, then adding some - again non-company-internal - commentary and/or details/code to replicate the problem on an existing issue thread could stir a few people back into activity.  `select2` seems fairly quiet nowadays so there's no guarantee, but sometimes open source bugs take a while to sit until someone has enough time and energy to collect the existing info and make progress, so adding more signal can help.  Maybe you know that already but I don't want to assume too much!

I also have one idea for something to look at: is `jquery-mousewheel` installed and working in your application?  [Including it](https://github.com/select2/select2/issues/2402#issuecomment-44108685) enables additional [`mousewheel` event-handler code](https://github.com/select2/select2/blob/4de1d236e602149a5c78d35899b49b3989b94107/src/js/select2/results.js#L427); whether that's at all related to your defect, I can't really tell -- my guess is not, because it sounds like it's the parent container's scrollability that is causing the problem -- but it's hopefully a fairly quick thing to check.

**Comment by jayaddison** [comment]
Also potentially relevant: I think @modolabs may have been working on something similar in their [fork of `select2`](https://github.com/modolabs/select2/).  I'm not certain, but the description of 87e50ebfceb58bc6f2f66542b63855573506f12c sounds similar to the problem you're trying to solve based on the title here.

**Comment by david-knipe395** [comment]
Yes, it looks like there's a similar fix there - more specifically
https://github.com/select2/select2/commit/87e50ebfceb58bc6f2f66542b63855573506f12c
.

As a matter of fact I ended up reverting my change on our side because,
while it fixed some cases, it broke others. I decided it was safer to work
around it in our own code than try to fix someone else's again.

But if I was going to fix it I would have done something like that: same as
what I had, but inside a conditional. From my limited investigation I'd
thought the condition might be something like `$offsetParent[0] ===
$("html")[0]`.

So that other fork may well be correct. Apart from the case where we have
horizontal but not vertical scrolling or vice versa - in that case it looks
like it does the adjustment for both, but should only do one of them. I
suppose there's still a bug in there.

David

**Comment by jayaddison** [comment]
cc @arkonan - I noticed that both you and @david-knipe395 here had been working on a similar fix in `select2` and there's some feedback here on your changes that may be relevant.

**Pull request merged**
